### ISSUE TITLE
Create test for addDevReward and getDevReward

### ISSUE THREAD

**Issue by sla-shi** [MFChain/smart-contracts#116]

**Comment by serebrov** [comment]
From #52:

**Summary:**
Using Truffle, we check method for _ICO_controller getDevReward()_ and test 2 moments:
- if the function reverted if devRewardReleaseTime >= now
- if the right amount of tokens transferred to address.

Test 3 variants:
- msg.sender in mapping and amount > 0
- msg.sender in mapping and amount = 0
- msg.sender not in mapping
