### ISSUE TITLE
Create test for Holder escrowSecondStage()

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#28]
**Summary:**
Using Truffle, we check method for _Holder - escrowSecondStage()_ and test the functionality of this method, if the Ether will come to escrow address, if the amount of ether is 100% of full amount holded in this contract on the moment of executing this method and if this method executed only when the required number of owners are call it.

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by Norfolks** [comment]
Not all
Only len(all_owners) - 1

**Comment by savao** [comment]
I mean - all needed number of owners, this number is in variable m_required not len(all_owners) - 1

**Comment by savao** [comment]
![t28.png](https://images.zenhubusercontent.com/5a3ca8258a75884b908bf1a9/b93aad78-ced2-4eb2-8adc-d47d12097842)
