### ISSUE TITLE
Create test for Holder revoke() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#29]
**Summary:**
Using Truffle, we check method for _Holder revoke()_ and test 4 moments:
- if the execution of this method remove agreement of this owner.
- if the execution of this method from address wich is not owner do nothing.
- if the execution of this method for operation, which is not in list do nothing.
- if the execution of this method for operation, which don't have agreement of this owner do nothing.

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by multiowned tests.
