### ISSUE TITLE
Create test for MFC_token transfer() with Truffle

### ISSUE THREAD

**Issue by sla-shi** [MFChain/smart-contracts#3]
**Summary:**
Using Truffle, we check method for _MFC_token transfer()_ and test 6 variants:
- if the sender have enough tokens and send to address
- if the sender have enough tokens and send to contract with tokenFallback()
- if the sender have enough tokens and send to contract without tokenFallback()
- if the sender have not enough tokens and send to address
- if the sender have zero balance and send to address
- if the sender have not balance and send to address

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by savao** [comment]
![t3.png](https://images.zenhubusercontent.com/5a3ca8258a75884b908bf1a9/940065cd-7089-4c33-8381-f2c805aa21a1)
