### ISSUE TITLE
Create test for Holder changeOwner() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#31]
**Summary:**
Using Truffle, we check method for _Holder changeOwner()_ and test if this method executed only when all owners are call it, if this method clear the pending table, if the changes of m_owners and m_ownerIndex are correct.

Test 3 variants:
- when _from is owner and _to is not owner
- when _from is not owner
- when _to is owner

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by multiowned tests.
