### ISSUE TITLE
Create test for Holder addOwner() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#32]
**Summary:**
Using Truffle, we check method for _Holder addOwner()_ and test if this method executed only when all owners are call it, if this method clear the pending table, if the changes of m_owners and m_ownerIndex are correct.

Test 3 variants:
- when _owner is not owner
- when _owner is owner
- when number of owners = c_maxOwners

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by multiowned tests.
