### ISSUE TITLE
Create test for Holder removeOwner() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#33]
**Summary:**
Using Truffle, we check method for _Holder removeOwner()_ and test if this method executed only when all owners are call it, if this method clear the pending table, if the changes of m_owners and m_ownerIndex are correct.

Test 3 variants:
- when _owner is owner and m_required < m_numOwners - 1
- when _owner is not owner and m_required < m_numOwners - 1
- when _owner is owner and m_required > m_numOwners - 1

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by multiowned tests.
