### ISSUE TITLE
Create test for Holder changeRequirement() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#34]
**Summary:**
Using Truffle, we check method for _Holder changeRequirement()_ and test if this method executed only when all owners are call it, if this method clear the pending table, if the change of m_required is correct.

Test 2 variants:
- when _newRequired > m_numOwners
- when _newRequired <= m_numOwners

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by avgoeid** [comment]
It was checked in tests for task 29
