### ISSUE TITLE
Create test for Holder hasConfirmed() with Truffle

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#35]
**Summary:**
Using Truffle, we check method for _Holder hasConfirmed()_ and test if the response of this method is correct.

Test 4 variants:
- _operation in m_pending, _owner is owner and _owner is confirmed this operation
- _operation in m_pending, _owner is owner and _owner is not confirmed this operation
- _operation in m_pending, _owner is not owner
- _operation not in m_pending, _owner is owner

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by multiowned tests.

**Comment by serebrov** [comment]
Covered by multiowned tests.
