### ISSUE TITLE
Create test for ICO_controller startCrowdsale()

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#50]
**Summary:**
Using Truffle, we check method for _ICO_controller startCrowdsale()_ and test 2 moments:
- if the contract of crowdsale for common crowdsale created correctly and right amount of tokens sends to contract.
- if the check for finishing of presale work correctly.

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by ICO stage tests.
