### ISSUE TITLE
Create test for ICO_controller finishCrowdsale()

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#51]
**Summary:**
Using Truffle, we check method for _ICO_controller finishCrowdsale()_ and test if the all checks work correctly, if the crowdsale remaining tokens burns.

Test 2 variants:
- totalSold >= SOFTCUP if the all Ether and tokens sended correctly
- totalSold < SOFTCUP if the all Ether and tokens remain on controller

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by ICO stage tests.
