### ISSUE TITLE
Create test for ICO_controller getDevReward()

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#52]
**Summary:**
Using Truffle, we check method for _ICO_controller getDevReward()_ and test 2 moments:
- if the function reverted if devRewardReleaseTime >= now
- if the right amount of tokens transferred to address.

Test 3 variants:
- msg.sender in mapping and amount > 0
- msg.sender in mapping and amount = 0
- msg.sender not in mapping

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Duplicate https://github.com/MFChain/smart-contracts/issues/116
