### ISSUE TITLE
Create test for ICO_controller refund()

### ISSUE THREAD

**Issue by savao** [MFChain/smart-contracts#54]
**Summary:**
Using Truffle, we check method for _ICO_controller refund()_ and test 4 moments:
- if the function reverted if the common crowdsale not ended.
- if the function reverted if the softcap reached.
- if the right amount of Ether refunded.
- if the buyerSpent[msg.sender] == 0 after refund.

**Output:**
After running the test with Truffle, please attach a screen to issue

**Comment by serebrov** [comment]
Covered by ICO stage tests.
